### PR TITLE
Load system policy contexts

### LINKED ISSUE #288: Fcontext fails on re-run on newer platforms
An example error from the console of what the module runs:

```
# /sbin/semanage fcontext -a -t squid_cache_t -f a '/var/spool/squid(/.*)?'
ValueError: File context for /var/spool/squid(/.*)? already defined
```

Package version:

```
policycoreutils-python-utils.noarch                                           2.8-16.1.el8                                        @rhel-8-for-x86_64-baseos-rpms                                               
```

Seems that newer semanage will error if a `-a` operating is ran for an existing entity which breaks re-runs.

### PR DESCRIPTION
**Pull request by ekohl**
This change prefetches the system policy contexts. This means that if the system policy already exists for `/var/spool/squid(/.*)?` then it won't attempt to override it when the specification matches. It does still allow modifications if for some reason the base policy is incorrect. Purging of all local contexts is also still possible.

Inspired by #289

Fixes #288

### CODE REVIEW

File: lib/puppet/provider/selinux_fcontext/semanage.rb [hunk 1]
```diff
@@ -66,22 +66,29 @@ def self.parse_fcontext_lines(lines)
...
-    end
+    self.parse_fcontext_file(Selinux.selinux_file_context_local_path)
+  end
+
+  def self.system_policy_instances
+    self.parse_fcontext_file(Selinux.selinux_file_context_path)
   end
 
   def self.prefetch(resources)
-    # is there a better way to do this? map port/protocol pairs to the provider regardless of the title
```
Comment (ekohl) [inline lib/puppet/provider/selinux_fcontext/semanage.rb]: Not sure if this comment still makes sense.
